quarkus:
    http:
        port: 8080
        auth:
            basic: true

    dev-ui:
        enabled: false

    datasource:
        db-kind: postgresql
        username: postgres
        password: postgres
        jdbc:
            url: jdbc:postgresql://localhost:5432/postgres

    hibernate-orm:
        database:
            generation: drop-and-create
        log:
            sql: true

    security:
        jdbc:
            enabled: true
            principal-query:
                sql: "SELECT password, role FROM users WHERE email = ?"
                clear-password-mapper:
                    enabled: false
                bcrypt-password-mapper:
                    enabled: true
                    password-index: 1
                    hash-encoding: hex
                attribute-mapping:
                    role: 2
