quarkus:
    http:
        port: 8080


    dev-ui:
        enabled: false

    datasource:
        db-kind: postgresql
        username: postgres
        password: postgres
        jdbc:
            url: jdbc:postgresql://localhost:5432/postgres

    hibernate-orm:
        database:
            generation: update
        log:
            sql: true


mp:
  jwt:
    verify:
      publickey:
        location: publicKey.pem
      issuer: http://myapp.example.com  # Change to your app's issuer, e.g., https://yourdomain.com

smallrye:
  jwt:
    expire:
      in: 3600  # Token expires in 1 hour (3600 seconds) â€“ adjust as needed
    sign:
      key:
        location: privateKey.pem